import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-ppo-aggregated',
  templateUrl: './ppo-aggregated.component.html',
  styleUrls: ['./ppo-aggregated.component.css']
})
export class PpoAggregatedComponent implements OnInit {
  gridOptions: SohoDataGridOptions = {};

  constructor() {}

  ngOnInit() {
    this.gridOptions = {
      columns: [
        {
          id: 'POSUNO',
          field: 'POSUNO',
          name: 'Supplier'
        },
        {
          id: 'POPRIP',
          field: 'POPRIP',
          name: 'Pri'
        },
        {
          id: 'POORTY',
          field: 'POORTY',
          name: 'Otp'
        },
        {
          id: 'PODLDT',
          field: 'PODLDT',
          name: 'Pl del',
          formatter: Soho.Formatters.Date
        },
        {
          id: 'POITNO',
          field: 'POITNO',
          name: 'Item number'
        },
        {
          id: 'MMITDS',
          field: 'MMITDS',
          name: 'Item name'
        },
        {
          id: 'POPUPR',
          field: 'POPUPR',
          name: 'Purchase price',
          align: 'right',
          formatter: Soho.Formatters.Decimal
        },
        {
          id: 'POPPQT',
          field: 'POPPQT',
          name: 'Plan qty',
          align: 'right',
          formatter: Soho.Formatters.Decimal
        },
        {
          id: 'POPUUN',
          field: 'POPUUN',
          name: 'PO U/M'
        },
        {
          id: 'MMNEWE',
          field: 'MMNEWE',
          name: 'Net weight',
          align: 'right',
          formatter: Soho.Formatters.Decimal
        },
        {
          id: 'MMGRTS',
          field: 'MMGRTS',
          name: 'D grp'
        },
        {
          id: 'POMSG1',
          field: 'POMSG1',
          name: 'Msg'
        },
        {
          id: 'POPSTS',
          field: 'POPSTS',
          name: 'Sts'
        },
        {
          id: 'NASCNB',
          field: 'NASCNB',
          name: 'Sup chn no'
        },
        {
          id: 'POACTP',
          field: 'POACTP',
          name: 'AM'
        }
      ],
      selectable: false,
      rowHeight: 'medium',
      groupable: {
        fields: ['POPPSQ'],
        expanded: true,
        aggregator: '',
        groupRowFormatter: (row, cell, value, col, item: any, api) => {
          const PPSQ = item.POPPSQ ? item.POPPSQ : 'BLANK';

          // Add custom-ppsq property that will be read by the button's evetn listener
          return (
            'Co-Sorting: <span style="background: #FA9601; padding: 4px 16px; color: white !important; border-radius: 16px; margin-left: 16px;">' +
            PPSQ +
            '</span><button type="button" class="btn-primary group-header-button" style="float: right;" selected-ppsq="' +
            item.POPPSQ +
            '">' +
            '<span>' +
            'Change' +
            '</span></button>'
          );
        }
      },
      dataset: [
        {
          POSUNO: '001',
          POWHLO: '530',
          POPLPN: 1158,
          POPLPS: 0,
          POPLP2: 0,
          POPRIP: '5',
          POORTY: 'R03',
          PODLDT: '2021-07-15T16:00:00.000Z',
          POITNO: 'VOE11715272',
          MMITDS: 'Oljefilter',
          POPUPR: 73.44,
          POPPQT: 4,
          POPUUN: 'ST',
          MMNEWE: 0.34,
          MMGRTS: '',
          POMSG1: '',
          POPSTS: '10',
          NASCNB: '',
          POACTP: 'A1',
          POPPSQ: '1'
        },
        {
          POSUNO: '001',
          POWHLO: '530',
          POPLPN: 1159,
          POPLPS: 0,
          POPLP2: 0,
          POPRIP: '5',
          POORTY: 'R03',
          PODLDT: '2021-07-15T16:00:00.000Z',
          POITNO: 'VOE11716756',
          MMITDS: 'Handpump',
          POPUPR: 153.11,
          POPPQT: 3,
          POPUUN: 'ST',
          MMNEWE: 0.052,
          MMGRTS: '',
          POMSG1: '',
          POPSTS: '10',
          NASCNB: '',
          POACTP: 'A1',
          POPPSQ: '3'
        },
        {
          POSUNO: '001',
          POWHLO: '530',
          POPLPN: 1161,
          POPLPS: 0,
          POPLP2: 0,
          POPRIP: '5',
          POORTY: 'R03',
          PODLDT: '2021-07-15T16:00:00.000Z',
          POITNO: 'VOE14689735',
          MMITDS: 'Hyttfilter',
          POPUPR: 250.56,
          POPPQT: 4,
          POPUUN: 'ST',
          MMNEWE: 0.483,
          MMGRTS: '',
          POMSG1: '',
          POPSTS: '10',
          NASCNB: '',
          POACTP: 'A1',
          POPPSQ: '1'
        },
        {
          POSUNO: '001',
          POWHLO: '530',
          POPLPN: 1168,
          POPLPS: 0,
          POPLP2: 0,
          POPRIP: '5',
          POORTY: 'R03',
          PODLDT: '2021-07-15T16:00:00.000Z',
          POITNO: 'VOE17214674',
          MMITDS: 'Tank',
          POPUPR: 1232.81,
          POPPQT: 3,
          POPUUN: 'ST',
          MMNEWE: 1.36,
          MMGRTS: '',
          POMSG1: '',
          POPSTS: '10',
          NASCNB: '',
          POACTP: 'A1',
          POPPSQ: '5'
        },
        {
          POSUNO: '001',
          POWHLO: '530',
          POPLPN: 1170,
          POPLPS: 0,
          POPLP2: 0,
          POPRIP: '5',
          POORTY: 'R03',
          PODLDT: '2021-07-15T16:00:00.000Z',
          POITNO: 'VOE17418113',
          MMITDS: 'Filterpatron',
          POPUPR: 765.18,
          POPPQT: 5,
          POPUUN: 'ST',
          MMNEWE: 1.959,
          MMGRTS: '',
          POMSG1: '',
          POPSTS: '10',
          NASCNB: '',
          POACTP: 'A1',
          POPPSQ: '5'
        },
        {
          POSUNO: '001',
          POWHLO: '530',
          POPLPN: 1176,
          POPLPS: 0,
          POPLP2: 0,
          POPRIP: '5',
          POORTY: 'R03',
          PODLDT: '2021-07-15T16:00:00.000Z',
          POITNO: 'VOE17480449',
          MMITDS: 'Grå spray',
          POPUPR: 109.48,
          POPPQT: 6,
          POPUUN: 'ST',
          MMNEWE: 0.429,
          MMGRTS: 'FG',
          POMSG1: '',
          POPSTS: '10',
          NASCNB: '',
          POACTP: 'A1',
          POPPSQ: '2'
        },
        {
          POSUNO: '001',
          POWHLO: '530',
          POPLPN: 1188,
          POPLPS: 0,
          POPLP2: 0,
          POPRIP: '5',
          POORTY: 'R03',
          PODLDT: '2021-07-15T16:00:00.000Z',
          POITNO: 'VOE4880700',
          MMITDS: 'Torkarblad',
          POPUPR: 131.24,
          POPPQT: 6,
          POPUUN: 'ST',
          MMNEWE: 0.294,
          MMGRTS: '',
          POMSG1: '',
          POPSTS: '10',
          NASCNB: '',
          POACTP: 'A1',
          POPPSQ: '3'
        },
        {
          POSUNO: '001',
          POWHLO: '530',
          POPLPN: 1192,
          POPLPS: 0,
          POPLP2: 0,
          POPRIP: '5',
          POORTY: 'R03',
          PODLDT: '2021-07-15T16:00:00.000Z',
          POITNO: 'VOE962500',
          MMITDS: 'O-ring',
          POPUPR: 120.06,
          POPPQT: 10,
          POPUUN: 'ST',
          MMNEWE: 0.036,
          MMGRTS: '',
          POMSG1: '',
          POPSTS: '10',
          NASCNB: '',
          POACTP: 'A1',
          POPPSQ: ''
        },
        {
          POSUNO: '001',
          POWHLO: '530',
          POPLPN: 1193,
          POPLPS: 0,
          POPLP2: 0,
          POPRIP: '5',
          POORTY: 'R03',
          PODLDT: '2021-07-15T16:00:00.000Z',
          POITNO: 'VOE977525',
          MMITDS: 'Kilrem',
          POPUPR: 267.38,
          POPPQT: 6,
          POPUUN: 'ST',
          MMNEWE: 0.204,
          MMGRTS: '',
          POMSG1: '',
          POPSTS: '10',
          NASCNB: '',
          POACTP: 'A1',
          POPPSQ: ''
        },
        {
          POSUNO: '001',
          POWHLO: '530',
          POPLPN: 1194,
          POPLPS: 0,
          POPLP2: 0,
          POPRIP: '5',
          POORTY: 'R03',
          PODLDT: '2021-07-15T16:00:00.000Z',
          POITNO: 'VOE978710',
          MMITDS: 'Kilrem',
          POPUPR: 153.7,
          POPPQT: 8,
          POPUUN: 'ST',
          MMNEWE: 0.108,
          MMGRTS: '',
          POMSG1: '',
          POPSTS: '10',
          NASCNB: '',
          POACTP: 'A1',
          POPPSQ: ''
        },
        {
          POSUNO: '001',
          POWHLO: '530',
          POPLPN: 1198,
          POPLPS: 0,
          POPLP2: 0,
          POPRIP: '5',
          POORTY: 'R03',
          PODLDT: '2021-07-15T16:00:00.000Z',
          POITNO: 'VOE990950',
          MMITDS: 'Flange lock nut',
          POPUPR: 7.54,
          POPPQT: 46,
          POPUUN: 'ST',
          MMNEWE: 0.013,
          MMGRTS: '',
          POMSG1: '',
          POPSTS: '10',
          NASCNB: '',
          POACTP: 'A1',
          POPPSQ: ''
        },
        {
          POSUNO: '001',
          POWHLO: '530',
          POPLPN: 1199,
          POPLPS: 0,
          POPLP2: 0,
          POPRIP: '5',
          POORTY: 'R03',
          PODLDT: '2021-07-15T16:00:00.000Z',
          POITNO: 'ZM 2905303',
          MMITDS: 'Filter',
          POPUPR: 43.74,
          POPPQT: 4,
          POPUUN: 'ST',
          MMNEWE: 0.34,
          MMGRTS: '',
          POMSG1: '',
          POPSTS: '10',
          NASCNB: '',
          POACTP: 'A1',
          POPPSQ: ''
        },
        {
          POSUNO: '001',
          POWHLO: '530',
          POPLPN: 1843,
          POPLPS: 0,
          POPLP2: 0,
          POPRIP: '5',
          POORTY: 'R03',
          PODLDT: '2021-07-15T16:00:00.000Z',
          POITNO: 'VOE11033999',
          MMITDS: 'Filter',
          POPUPR: 402.84,
          POPPQT: 5,
          POPUUN: 'ST',
          MMNEWE: 1.36,
          MMGRTS: '',
          POMSG1: '',
          POPSTS: '10',
          NASCNB: '',
          POACTP: 'A1',
          POPPSQ: '3'
        },
        {
          POSUNO: '001',
          POWHLO: '530',
          POPLPN: 1844,
          POPLPS: 0,
          POPLP2: 0,
          POPRIP: '5',
          POORTY: 'R03',
          PODLDT: '2021-07-15T16:00:00.000Z',
          POITNO: 'VOE11110023',
          MMITDS: 'Luftfilter',
          POPUPR: 370.98,
          POPPQT: 8,
          POPUUN: 'ST',
          MMNEWE: 1.065,
          MMGRTS: '',
          POMSG1: '',
          POPSTS: '10',
          NASCNB: '',
          POACTP: 'A1',
          POPPSQ: '1'
        },
        {
          POSUNO: '001',
          POWHLO: '530',
          POPLPN: 1845,
          POPLPS: 0,
          POPLP2: 0,
          POPRIP: '5',
          POORTY: 'R03',
          PODLDT: '2021-07-15T16:00:00.000Z',
          POITNO: 'VOE11705485',
          MMITDS: 'Filter.opt',
          POPUPR: 1686.42,
          POPPQT: 2,
          POPUUN: 'ST',
          MMNEWE: 1.179,
          MMGRTS: '',
          POMSG1: '',
          POPSTS: '10',
          NASCNB: '',
          POACTP: 'A1',
          POPPSQ: '2'
        },
        {
          POSUNO: '001',
          POWHLO: '530',
          POPLPN: 1846,
          POPLPS: 0,
          POPLP2: 0,
          POPRIP: '5',
          POORTY: 'R03',
          PODLDT: '2021-07-15T16:00:00.000Z',
          POITNO: 'VOE14511215',
          MMITDS: 'O-ring',
          POPUPR: 76.56,
          POPPQT: 3,
          POPUUN: 'ST',
          MMNEWE: 0.006,
          MMGRTS: '',
          POMSG1: '',
          POPSTS: '10',
          NASCNB: '',
          POACTP: 'A1',
          POPPSQ: '4'
        },
        {
          POSUNO: '001',
          POWHLO: '530',
          POPLPN: 1847,
          POPLPS: 0,
          POPLP2: 0,
          POPRIP: '5',
          POORTY: 'R03',
          PODLDT: '2021-07-15T16:00:00.000Z',
          POITNO: 'VOE14662207',
          MMITDS: 'Filter',
          POPUPR: 1745.82,
          POPPQT: 2,
          POPUUN: 'ST',
          MMNEWE: 5.556,
          MMGRTS: '',
          POMSG1: '',
          POPSTS: '10',
          NASCNB: '',
          POACTP: 'A1',
          POPPSQ: '2'
        },
        {
          POSUNO: '001',
          POWHLO: '530',
          POPLPN: 1848,
          POPLPS: 0,
          POPLP2: 0,
          POPRIP: '5',
          POORTY: 'R03',
          PODLDT: '2021-07-15T16:00:00.000Z',
          POITNO: 'VOE17410282',
          MMITDS: 'Filter element',
          POPUPR: 326.16,
          POPPQT: 2,
          POPUUN: 'ST',
          MMNEWE: 0.666,
          MMGRTS: '',
          POMSG1: '',
          POPSTS: '10',
          NASCNB: '',
          POACTP: 'A1',
          POPPSQ: ''
        },
        {
          POSUNO: '001',
          POWHLO: '530',
          POPLPN: 1849,
          POPLPS: 0,
          POPLP2: 0,
          POPRIP: '5',
          POORTY: 'R03',
          PODLDT: '2021-07-15T16:00:00.000Z',
          POITNO: 'VOE20998807',
          MMITDS: 'Oil filter',
          POPUPR: 170.64,
          POPPQT: 18,
          POPUUN: 'ST',
          MMNEWE: 0.327,
          MMGRTS: '',
          POMSG1: '',
          POPSTS: '10',
          NASCNB: '',
          POACTP: 'A1',
          POPPSQ: ''
        },
        {
          POSUNO: '001',
          POWHLO: '530',
          POPLPN: 1850,
          POPLPS: 0,
          POPLP2: 0,
          POPRIP: '5',
          POORTY: 'R03',
          PODLDT: '2021-07-15T16:00:00.000Z',
          POITNO: 'VOE960254',
          MMITDS: 'O-ring',
          POPUPR: 102.08,
          POPPQT: 5,
          POPUUN: 'ST',
          MMNEWE: 0.022,
          MMGRTS: '',
          POMSG1: '',
          POPSTS: '10',
          NASCNB: '',
          POACTP: 'A1',
          POPPSQ: ''
        },
        {
          POSUNO: '001',
          POWHLO: '530',
          POPLPN: 2556,
          POPLPS: 0,
          POPLP2: 0,
          POPRIP: '5',
          POORTY: 'R03',
          PODLDT: '2021-07-15T16:00:00.000Z',
          POITNO: 'VOE11033998',
          MMITDS: 'Luftfilter',
          POPUPR: 651.78,
          POPPQT: 7,
          POPUUN: 'ST',
          MMNEWE: 4.28,
          MMGRTS: '',
          POMSG1: '',
          POPSTS: '10',
          NASCNB: '',
          POACTP: 'A1',
          POPPSQ: '3'
        }
      ]
    };
  }
}
